// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oysbzajjyhkzybsuavhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95c2J6YWpqeWhrenlic3VhdmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzMyNjgsImV4cCI6MjA2MjE0OTI2OH0.of3S-F125bO-dIyvJCn0zY9Asl6i_TtvrgU80xcO1jE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);